# Machine Learning Zoomcamp

## Week 01: Introduction to Machine Learning


### 1.7 Introduction to Numpy

Plan:

* Creating Arrays
* Multi-dimentional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

---

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\HP\\anaconda3\\envs\\ml-zoomcamp\\lib\\site-packages\\numpy\\__init__.py'>

### Creating arrays

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [8]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multi-dementional arrays

In [10]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [12]:
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [13]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [14]:
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

### Randomly generated arrays

In [15]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [16]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [17]:
np.random.seed(2)
np.random.randint(low = 0, high = 100, size = (5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### Element-wise operations

In [18]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [19]:
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [20]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

### Comparison operations 

In [21]:
a

array([0, 1, 2, 3, 4])

In [22]:
a >= 2

array([False, False,  True,  True,  True])

In [23]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [24]:
a > b

array([False, False,  True,  True,  True])

In [25]:
a[a > b]

array([2, 3, 4])

### Summarizing operations 

In [26]:
a

array([0, 1, 2, 3, 4])

In [27]:
a.std()

1.4142135623730951

In [28]:
n.min()

0